name: lando-website
services:
  node:
    type: node:18
    build:
      - npm install
    scanner: false
    ssl: false
    sslExpose: false
    overrides:
      ports:
        - 8010:8010
tooling:
  node:
    service: node
  npm:
    service: node

