[build]
  base = "./"
  publish = ".vuepress/dist"
  command = "rm -rf node_modules && npm ci && npm run build"

# Sets our asset optimization
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

# Caches our images for 1 year
[[headers]]
  for = "/images/*"
  [headers.values]
	  Cache-Control = "public, max-age=31536000"

# https://github.com/munter/netlify-plugin-checklinks#readme
[[context.deploy-preview.plugins]]
  package = "netlify-plugin-checklinks"
  [context.deploy-preview.plugins.inputs]
    todoPatterns = [ "self-signed certificate", "hub.docker.com", " https://github.com/issues" ]
    skipPatterns = [ ".rss", ".gif", ".jpg", 'fonts.googleapis.com', 'https://www.lando.dev/blog', 'https://www.lando.dev/events', 'x.com', 'twitter.com' ]
    checkExternal = true

# pluginz
# https://github.com/netlify/netlify-plugin-lighthouse#readme
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"

# Domain redirects
[[redirects]]
  from = "https://devwithlando.io/*"
  to = "https://www.lando.dev/:splat"
  status = 301
[[redirects]]
  from = "https://lndo.io/*"
  to = "https://www.lando.dev/:splat"
  status = 301

# .html to / redirects
[[redirects]]
  from = "/contact.html"
  to = "/contact"
  status = 301
[[redirects]]
  from = "/download.html"
  to = "https://docs.lando.dev/install"
  status = 301
[[redirects]]
  from = "/download"
  to = "https://docs.lando.dev/install"
  status = 301
[[redirects]]
  from = "/download/"
  to = "https://docs.lando.dev/install"
  status = 301
[[redirects]]
  from = "/features.html"
  to = "/features"
  status = 301
[[redirects]]
  from = "/coc.html"
  to = "/coc"
  status = 301
[[redirects]]
  from = "/privacy.html"
  to = "/privacy"
  status = 301
[[redirects]]
  from = "/support.html"
  to = "/support"
  status = 301
[[redirects]]
  from = "/terms.html"
  to = "/terms"
  status = 301
[[redirects]]
  from = "/get"
  to = "https://docs.lando.dev/install"
  status = 301
[[redirects]]
  from = "/get/"
  to = "https://docs.lando.dev/install"
  status = 301
[[redirects]]
  from = "/about"
  to = "/mission/"
  status = 301
[[redirects]]
  from = "/about/"
  to = "/mission/"
  status = 301
[[redirects]]
  from = "/nonprofit"
  to = "/mission/"
  status = 301
[[redirects]]
  from = "/nonprofit/"
  to = "/mission/"
  status = 301
[[redirects]]
  from = "/donate"
  to = "https://github.com/sponsors/lando"
  status = 302
[[redirects]]
  from = "/donate/"
  to = "https://github.com/sponsors/lando"
  status = 302

# API routes
[[redirects]]
  from = "/api/lando-stats"
  to = "/.netlify/functions/lando-stats"
  status = 200

# Subsite redirects
[[redirects]]
  from = "/blog"
  to = "https://lando-blog.netlify.app"
  status = 200
  force = true
[[redirects]]
  from = "/blog/*"
  to = "https://lando-blog.netlify.app/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/blog.html"
  to = "https://lando-blog.netlify.app"
  status = 200
  force = true
[[redirects]]
  from = "/events"
  to = "https://lando-events.netlify.app"
  status = 200
  force = true
[[redirects]]
  from = "/events/*"
  to = "https://lando-events.netlify.app/:splat"
  status = 200
  force = true

# Legacy redirects from cloudflare
[[redirects]]
  from = "/sponsor"
  to = "https://github.com/sponsors/lando"
  status = 302
[[redirects]]
  from = "/sponsor/"
  to = "https://github.com/sponsors/lando"
  status = 302
[[redirects]]
  from = "/join"
  to = "https://docs.lando.dev/contrib/contributing.html"
  status = 301
[[redirects]]
  from = "/join/"
  to = "https://docs.lando.dev/contrib/contributing.html"
  status = 301
[[redirects]]
  from = "/alliance/join"
  to = "https://docs.lando.dev/contrib/contributing.html"
  status = 301
[[redirects]]
  from = "/alliance/join/"
  to = "https://docs.lando.dev/contrib/contributing.html"
  status = 301
