name: Run Tests

on:
  pull_request:

jobs:
  build-tests:
    runs-on: ubuntu-22.04
    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm
      - name: Install dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile

      # Run tests
      - name: Run linter
        run: npm run lint
      - name: Test build
        run: npm run build
